version: '3.2'

networks:
  backend:
    external:
      name: service_network

services:
  keycloak_server:
    image: jboss/keycloak:latest
    container_name: keycloak
    restart: on-failure
    ports:      
      - '8080:8080'
    environment:
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_USER: root
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_mysql_server
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: password      
    networks:
      backend:
        aliases:
          - keycloak


  keycloak_mysql_server:
    image: mysql
    container_name: keycloak_mysql
    restart: on-failure
    ports:      
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - backend
    volumes:
      - keycloakdata:/var/lib/mysql

volumes:
  keycloakdata:

